PX4 integration
01org/mavlink-vehicles pull request #28
Opened 2016-10-17 14:13 UTC by guiccbr

This Pull Request integrates PX4 specific modes and commands into mavlink_vehicles and also implement some other general changes. The commits specifically related to PX4 are prefixed with PX4.

Currently, the flight stack (PX4 or APM-ardupilot) needs to be selected statically into mavlink_vehicles.hh, but a commit that implements the auto-detection of the flight stack will be submitted soon.

2016-10-17 14:15 UTC, guiccbr commented on mavlink_vehicles/mavlink_vehicles.cc
> +enum PX4_CUSTOM_MAIN_MODE {
I'm not sure if this is the best place to keep these definitions. Qgroundcontrol keeps PX4 and APM definitions in separate files into a firmware folder. Should we do something similar? @rchiossi

2016-10-17 14:24 UTC, guiccbr commented on mavlink_vehicles/mavlink_vehicles.cc
> +    if (this->flight_stack_type == firmware_type::PX4) {
This check ideally should not be necessary. However, PX4 only accepts global yaw while Ardupilot accepts only relative yaw. Ardupilot should accept global yaw, but it is not working as expected probably because of a bug within its code. It might be an easy fix, but I did not have the opportunity to take a look into it yet.

2016-10-18 13:12 UTC, rchiossi requested changes
I think you can work on integrating the first 3 commits as they will be faster to integrate, then send the other 2 into a separate pr.

2016-10-18 13:12 UTC, rchiossi commented on mavlink_vehicles/mavlink_vehicles.cc
> +        }
Is it true that mission_items_list_received.size() can only be one item shorter than mission_items_list_received_size?

2016-10-18 13:12 UTC, rchiossi commented on mavlink_vehicles/mavlink_vehicles.cc
> +                                            &mav_mission_request);
Can't you use mavlink_msg_mission_request_list_pack instead? This way you don't need to create the mavlink_mission_request_list_t object.

2016-10-18 13:12 UTC, rchiossi commented on mavlink_vehicles/mavlink_vehicles.cc
> +    // Check if cmd_custom has been sent recently
This comment sounds a bit off since cmd_custom is not a command per se.

2016-10-18 13:12 UTC, rchiossi commented on mavlink_vehicles/mavlink_vehicles.cc
> +    // instance if system_id is no provided by the caller.
s/no/not

2016-10-18 13:12 UTC, rchiossi commented on mavlink_vehicles/mavlink_vehicles.cc
>      if (getsockname(this->sock, (struct sockaddr *)&our_addr, &our_addr_len) == -1) {
you removed the attribution of this->sock up there but you are still using it here.

2016-10-18 13:12 UTC, rchiossi commented on mavlink_vehicles/mavlink_vehicles.cc
> +        print_verbose("The socket provided to the constructor is invalid\n");
this error message shouldn't be the same as the one in the constructor.

2016-10-18 13:12 UTC, rchiossi commented on mavlink_vehicles/mavlink_vehicles.cc
>      }
why don't you use check_socket in here?

2016-10-18 13:12 UTC, rchiossi commented on mavlink_vehicles/mavlink_vehicles.cc
> +enum PX4_CUSTOM_MAIN_MODE {
Hmm, I'm not sure, but the .cc file doesn't look like a good place for it. If you don't want those exposed by the main header, you could have them in a private header that is imported by this file. Also, do we want the binary to be able to do PX4 and Ardupilot in runtime or do we want to select the autopilot in compile time?

2016-10-18 13:12 UTC, rchiossi commented on mavlink_vehicles/mavlink_vehicles.cc
> +            if (!(hb.base_mode & 157)) {
this 157 needs to be a constant or define.

2016-10-18 13:12 UTC, rchiossi commented on mavlink_vehicles/mavlink_vehicles.cc
> +            mav_cmd_set_mode.base_mode = 157;
Same as before.

2016-10-18 13:12 UTC, rchiossi commented on mavlink_vehicles/mavlink_vehicles.cc
> +            px4_mode.sub_mode = 0;
is this an specific mode or are you unsetting the variable?

2016-10-18 13:12 UTC, rchiossi commented on mavlink_vehicles/mavlink_vehicles.cc
> +            mav_cmd_set_mode.custom_mode = 4;
What is custom_mode 4?

2016-10-18 13:12 UTC, rchiossi commented on mavlink_vehicles/mavlink_vehicles.cc
> +    }
This can be removed since you already do that in set_yaw_target()

2016-10-18 13:12 UTC, rchiossi commented on mavlink_vehicles/mavlink_vehicles.hh
> +    firmware_type flight_stack_type = firmware_type::APM;
Add a TODO here as a reminder.

2016-10-18 13:12 UTC, rchiossi commented on mavlink_vehicles/mavlink_vehicles.cc
> +        // a custom mode instead. AUTO mode is defined as 3.
I think these comments are misplaced.

2016-10-18 13:12 UTC, rchiossi commented on mavlink_vehicles/mavlink_vehicles.cc
> +        mav_cmd_set_mode.base_mode = 157;
Same as previous patch. Specify what 157 is.

2016-10-18 13:12 UTC, rchiossi commented on mavlink_vehicles/mavlink_vehicles.cc
> +    case mode::TAKEOFF: {
return if firmware is not PX4

2016-10-18 13:12 UTC, rchiossi commented on mavlink_vehicles/mavlink_vehicles.cc
> +    float arm = arm_disarm ? 1.0 : 0.0;
float arm = (float) arm_disarm;

2016-10-18 13:12 UTC, rchiossi commented on mavlink_vehicles/mavlink_vehicles.cc
> +    this->set_mode(mode::TAKEOFF);
shouldn't this check for firmware?

2016-10-18 14:19 UTC, guiccbr commented on mavlink_vehicles/mavlink_vehicles.cc
> +enum PX4_CUSTOM_MAIN_MODE {
I think I will create two new headers then: px4.hh and apm.hh. The first will have these definitions and other px4 specific constants while in the second I will keep the the ardupilot constants, as [this](https://github.com/01org/mavlink-vehicles/pull/28/files#r83846026) one. Currently we're selecting the autopilot in compile time, but we want to detect it in runtime in the future. I will send a separate patch with that feature.

2016-10-18 14:20 UTC, guiccbr commented on mavlink_vehicles/mavlink_vehicles.cc
> +            if (!(hb.base_mode & 157)) {
I'll put it into px4.hh

2016-10-18 14:36 UTC, guiccbr commented on mavlink_vehicles/mavlink_vehicles.cc
> +        }
The mission items are indexed as [0, 1, 2, ..., size-1]. All items will have been already received when mission_item_list_received.size() == mission_item_list_received_size. When that happens we wont need to request any other item. Is that what you mean?

Also, I think I will change the names of these variables. It seems a little confusing.

2016-10-18 14:57 UTC, rchiossi commented on mavlink_vehicles/mavlink_vehicles.cc
> +enum PX4_CUSTOM_MAIN_MODE {
I asked because if you want to do it in runtime, maybe we should isolate the px4 and amp parts and just compile the one that matters. This way there is no need to branch and check for which autopilot we are using.

2016-10-18 15:45 UTC, rchiossi commented on mavlink_vehicles/mavlink_vehicles.cc
> +        }
nvm, I I misunderstood what the code was doing here.

2016-10-18 17:27 UTC, guiccbr commented on mavlink_vehicles/mavlink_vehicles.cc
> +                                            &mav_mission_request);
ack

2016-10-18 17:30 UTC, guiccbr commented on mavlink_vehicles/mavlink_vehicles.cc
> +    // Check if cmd_custom has been sent recently
ack

2016-10-18 17:31 UTC, guiccbr commented on mavlink_vehicles/mavlink_vehicles.cc
> +    // instance if system_id is no provided by the caller.
ack

2016-10-18 17:31 UTC, guiccbr commented on mavlink_vehicles/mavlink_vehicles.cc
>      if (getsockname(this->sock, (struct sockaddr *)&our_addr, &our_addr_len) == -1) {
ack

2016-10-18 17:32 UTC, guiccbr commented on mavlink_vehicles/mavlink_vehicles.cc
>      }
This was a little messy. I'll have it fixed.

2016-10-18 17:32 UTC, guiccbr commented on mavlink_vehicles/mavlink_vehicles.cc
> +        print_verbose("The socket provided to the constructor is invalid\n");
ack

2016-10-18 17:42 UTC, guiccbr commented
Reviewed and separated into two patches.

2016-10-18 17:42 UTC, closed without merging

2016-10-19 01:17 UTC, guiccbr commented on mavlink_vehicles/mavlink_vehicles.cc
> +        mav_cmd_set_mode.base_mode = 157;
Using MAV_MODE_FLAG enum instead.

2016-10-19 01:26 UTC, guiccbr commented on mavlink_vehicles/mavlink_vehicles.cc
> +    float arm = arm_disarm ? 1.0 : 0.0;
ack

2016-10-19 01:46 UTC, guiccbr commented on mavlink_vehicles/mavlink_vehicles.cc
> +            mav_cmd_set_mode.base_mode = 157;
Using enum instead

2016-10-19 01:46 UTC, guiccbr commented on mavlink_vehicles/mavlink_vehicles.cc
> +            px4_mode.sub_mode = 0;
PX4 doesn't have a GUIDED mode. In order to achieve a similar behavior we need to put PX4 in OFFBOARD mode by sending a specific custom_mode composed by the main mode PX4_CUSTOM_MAIN_MODE_OFFBOARD and an empty sub_mode.

2016-10-19 01:46 UTC, guiccbr commented on mavlink_vehicles/mavlink_vehicles.cc
> +            mav_cmd_set_mode.custom_mode = 4;
Moved its definition to apm.hh

2016-10-19 01:58 UTC, guiccbr commented on mavlink_vehicles/mavlink_vehicles.cc
> +    }
set_yaw_target() and send_mission_waypoint() are not related. We need to make sure both of them change the mode to GUIDED independently.

2016-10-19 01:59 UTC, guiccbr commented on mavlink_vehicles/mavlink_vehicles.cc
> +        mav_cmd_set_mode.base_mode = 157;
using MAV enum instead

2016-10-19 02:05 UTC, guiccbr commented on mavlink_vehicles/mavlink_vehicles.cc
> +    case mode::TAKEOFF: {
ack

2016-10-19 02:06 UTC, guiccbr commented on mavlink_vehicles/mavlink_vehicles.cc
> +        // a custom mode instead. AUTO mode is defined as 3.
Agree, thanks.

2016-10-19 02:18 UTC, guiccbr commented on mavlink_vehicles/mavlink_vehicles.cc
> +    this->set_mode(mode::TAKEOFF);
You're right. This would brake Ardupilot Takeoff.