Document the API
01org/mavlink-vehicles pull request #41
Opened 2016-11-10 19:36 UTC by guiccbr

2016-11-30 13:14 UTC, guiccbr commented
@rchiossi, @mbelluzzo, can you take a look please?

2016-12-07 20:43 UTC, mbelluzzo requested changes

2016-12-07 20:43 UTC, mbelluzzo commented on src/px4.hh
> +//! PX4 custom main modes
Plz add "@brief" everywhere because we discovery while documenting Soletta that it does make a difference where doxygen do summary of structures and enumerations

2016-12-07 20:43 UTC, mbelluzzo commented on src/px4.hh
> +//! PX4 custom mode storage
What about s/storage/data type/ ?

2016-12-07 20:43 UTC, mbelluzzo commented on src/mavlink_vehicles.hh
> +    int32_t alt; //! @brief Millimeters (AMSL)
There is something odd happening here:

![screenshot from 2016-12-07 12-41-12](https://cloud.githubusercontent.com/assets/1584229/20985742/96895e44-bc7a-11e6-9898-656df4c19d77.png)

2016-12-08 15:00 UTC, guiccbr commented on src/px4.hh
> +//! PX4 custom main modes
Sure. Fixed in ec0db4d8cb6ec22098d53e7a3b99445e76458ba8.

2016-12-08 15:00 UTC, guiccbr commented on src/px4.hh
> +//! PX4 custom mode storage
Agree. Fix: 9356436761118359c043a39d7e1070a13ecb0cc1

2016-12-08 15:01 UTC, guiccbr commented on src/mavlink_vehicles.hh
> +    int32_t alt; //! @brief Millimeters (AMSL)
Fixed in ea0082efa5712c7d66ab3f41a28123fc269dedf2

2016-12-08 17:03 UTC, guiccbr commented
76c670c1fed94b56570406ea8b168ac3bf0d9974: Changed Doxyfile.in in order to use README.md as the main page of Doxygen.

2020-05-08 17:46 UTC, mbelluzzo approved these changes

2020-05-08 17:47 UTC, merged